# Generated by Django 5.1.6 on 2025-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Short code like FRESH, TRANSFER, PROMOTED, etc.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Descriptive name of the enrollment type.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional longer explanation for internal use.', null=True)),
            ],
            options={
                'verbose_name': 'Student Enrollment Type',
                'verbose_name_plural': 'Student Enrollment Types',
                'ordering': ['code'],
            },
        ),
    ]
