# Generated by Django 5.1.6 on 2025-04-22 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroupStudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(help_text='Date when the student was enrolled in this class group.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if this enrollment is currently active.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this enrollment (manual remarks, exceptions, etc.).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('class_group', models.ForeignKey(help_text='The class group the student is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='the_school.classgroup')),
                ('enrollment_type', models.ForeignKey(help_text='The reason or method of enrollment (e.g., Transfer, Fresh).', on_delete=django.db.models.deletion.PROTECT, to='enrollments.studentenrollmenttype')),
                ('student', models.ForeignKey(help_text='The student being enrolled.', on_delete=django.db.models.deletion.CASCADE, related_name='class_group_enrollments', to='users.student')),
            ],
            options={
                'verbose_name': 'Class Group Student Enrollment',
                'verbose_name_plural': 'Class Group Student Enrollments',
                'ordering': ['-enrollment_date', 'student'],
                'unique_together': {('student', 'class_group')},
            },
        ),
    ]
