# Generated by Django 5.1.6 on 2025-04-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_classgroupstudentenrollment'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_notes', models.TextField(blank=True, help_text="Optional notes about the teacher's qualifications, certifications, or experience.", null=True)),
                ('subject', models.ForeignKey(help_text='The subject the teacher is qualified to teach.', on_delete=django.db.models.deletion.CASCADE, related_name='qualified_teachers', to='the_school.subject')),
                ('teacher', models.ForeignKey(help_text='The teacher qualified to teach the subject.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_qualifications', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Subject Qualification',
                'verbose_name_plural': 'Teacher Subject Qualifications',
                'ordering': ['teacher', 'subject'],
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
