# Generated by Django 5.1.6 on 2025-04-22 12:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_teachersubjectqualification'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of when the teacher was assigned to the department.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this department assignment is currently active.')),
                ('department', models.ForeignKey(help_text='The department the teacher is assigned to.', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_teachers', to='the_school.department')),
                ('teacher', models.OneToOneField(help_text='The teacher being assigned to a department.', on_delete=django.db.models.deletion.CASCADE, related_name='department_assignment', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Department Assignment',
                'verbose_name_plural': 'Teacher Department Assignments',
            },
        ),
    ]
