# Generated by Django 5.1.6 on 2025-04-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_teacherdepartmentassignment'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubjectqualification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teachersubjectqualification',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teachersubjectqualification',
            name='teacher',
        ),
        migrations.CreateModel(
            name='TeacherSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teaching', models.BooleanField(default=True, help_text='Check if the teacher is actively teaching this subject currently.')),
                ('department_affiliation', models.ForeignKey(help_text='The department where the teacher officially works (e.g., Humanities Department).', on_delete=django.db.models.deletion.PROTECT, related_name='affiliated_teachers', to='the_school.department')),
                ('subject_assigned', models.ForeignKey(help_text='The specific subject the teacher is teaching.', on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='the_school.subject')),
                ('teacher', models.ForeignKey(help_text='The teacher who is assigned to the subject.', on_delete=django.db.models.deletion.PROTECT, related_name='subject_enrollments', to='users.teacher')),
                ('teaching_speciality_department', models.ForeignKey(help_text='The subject area the teacher is qualified to teach (e.g., Mathematics).', on_delete=django.db.models.deletion.PROTECT, related_name='specialist_teachers', to='the_school.department')),
            ],
            options={
                'verbose_name': 'Teacher Subject Enrollment',
                'verbose_name_plural': 'Teacher Subject Enrollments',
            },
        ),
        migrations.DeleteModel(
            name='TeacherDepartmentAssignment',
        ),
        migrations.DeleteModel(
            name='TeacherSubjectQualification',
        ),
        migrations.AddConstraint(
            model_name='teachersubjectenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('department_affiliation', models.F('teaching_speciality_department')), _negated=True), name='enrollments_teachersubjectenrollment_diff_affil_and_speciality'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectenrollment',
            unique_together={('teacher', 'subject_assigned')},
        ),
    ]
