# Generated by Django 5.1.6 on 2025-04-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_teachersubjectqualification_unique_together_and_more'),
        ('the_school', '0006_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectenrollment',
            name='subject_assigned',
            field=models.ForeignKey(blank=True, help_text='The specific subject the teacher is teaching.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='the_school.subject'),
        ),
    ]
