# Generated by Django 5.1.6 on 2025-04-22 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_teachersubjectenrollment_subject_assigned'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDepartmentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Optional: Academic year for this enrollment (e.g., 2025).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_school.academicyear')),
                ('department', models.ForeignKey(help_text='The department the teacher is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_enrollments', to='the_school.department')),
                ('teacher', models.ForeignKey(help_text='The teacher being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='department_enrollments', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Department Enrollment',
                'verbose_name_plural': 'Teacher Department Enrollments',
                'ordering': ['-date_assigned'],
            },
        ),
        migrations.DeleteModel(
            name='TeacherSubjectEnrollment',
        ),
        migrations.AddConstraint(
            model_name='teacherdepartmentenrollment',
            constraint=models.UniqueConstraint(fields=('teacher', 'department', 'academic_year'), name='unique_teacher_department_enrollment'),
        ),
    ]
