# Generated by Django 5.1.6 on 2025-04-22 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_teacherdepartmentenrollment_and_more'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Optional: The academic year of the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_school.academicyear')),
                ('subject', models.ForeignKey(help_text='The subject this teacher is responsible for.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='the_school.subject')),
                ('teacher', models.OneToOneField(help_text='The teacher being assigned to a subject.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignment', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'ordering': ['-date_assigned'],
                'unique_together': {('teacher', 'academic_year')},
            },
        ),
    ]
