# Generated by Django 5.1.6 on 2025-04-22 21:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0008_teachersubjectassignment'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Optional: Academic year of the HOD assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_school.academicyear')),
                ('department', models.ForeignKey(help_text='The department the teacher will head.', on_delete=django.db.models.deletion.CASCADE, related_name='hod_assignments', to='the_school.department')),
                ('teacher', models.ForeignKey(help_text='The teacher being assigned as HOD.', on_delete=django.db.models.deletion.CASCADE, related_name='hod_assignments', to='users.teacher')),
            ],
            options={
                'verbose_name': 'HOD Teacher Assignment',
                'verbose_name_plural': 'HOD Teacher Assignments',
                'ordering': ['-date_assigned'],
                'unique_together': {('department', 'academic_year'), ('teacher', 'academic_year')},
            },
        ),
    ]
