# Generated by Django 5.1.6 on 2025-04-22 21:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0009_hodteacherassignment'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroupTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now, help_text='The date the assignment was created.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active.')),
                ('academic_year', models.ForeignKey(blank=True, help_text='Optional academic year of the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='the_school.academicyear')),
                ('class_group', models.ForeignKey(help_text='The class group the teacher will lead.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='the_school.classgroup')),
                ('teacher', models.ForeignKey(help_text='The teacher being assigned to a class group.', on_delete=django.db.models.deletion.CASCADE, related_name='classgroup_assignments', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Class Group Teacher Assignment',
                'verbose_name_plural': 'Class Group Teacher Assignments',
                'ordering': ['-date_assigned'],
                'unique_together': {('class_group', 'academic_year'), ('teacher', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='HODTeacherAssignment',
        ),
    ]
