# Generated by Django 5.1.6 on 2025-04-23 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0010_classgroupteacherassignment_and_more'),
        ('the_school', '0006_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroupSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=django.utils.timezone.now, help_text='Date when this subject was assigned to the class group.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently active in the class group.')),
                ('academic_year', models.ForeignKey(help_text='The academic year this assignment applies to.', on_delete=django.db.models.deletion.CASCADE, to='the_school.academicyear')),
                ('class_group', models.ForeignKey(help_text='Class group to which the subject is being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='the_school.classgroup')),
                ('subject', models.ForeignKey(help_text='The subject being taught to the class group.', on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='the_school.subject')),
            ],
            options={
                'verbose_name': 'ClassGroup Subject Assignment',
                'verbose_name_plural': 'ClassGroup Subject Assignments',
                'ordering': ['-date_assigned'],
                'unique_together': {('class_group', 'subject', 'academic_year')},
            },
        ),
    ]
