# Generated by Django 5.1.6 on 2025-04-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Final Exam', max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight as percentage (e.g. 40 for 40%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Exam Type',
                'verbose_name_plural': 'Exam Type',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique identifier for this grading scale, e.g., 'CAPS 2024'.", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description providing details or context for this grading scale.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when this grading scale was created.')),
            ],
            options={
                'verbose_name': 'Exam Grade Scale',
                'verbose_name_plural': 'Exam Grade Scales',
            },
        ),
        migrations.CreateModel(
            name='GradeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(help_text='Letter grade representation (e.g., A+, B, C).', max_length=3)),
                ('min_percentage', models.DecimalField(decimal_places=2, help_text='Minimum percentage required to achieve this grade.', max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, help_text='Maximum percentage allowed for this grade.', max_digits=5)),
                ('scale', models.ForeignKey(help_text='The grading scale to which this grade range belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='grade_ranges', to='exams.gradescale')),
            ],
            options={
                'ordering': ['-min_percentage'],
                'unique_together': {('scale', 'letter')},
            },
        ),
    ]
