# Generated by Django 5.1.6 on 2025-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderange',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Optional points equivalent for GPA/weighting.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='graderange',
            name='letter',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='graderange',
            name='max_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graderange',
            name='min_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
