# Generated by Django 5.1.6 on 2025-04-23 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_graderange_points_alter_graderange_letter_and_more'),
        ('the_school', '0006_subject'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_conducted', models.DateField(default=django.utils.timezone.now)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('exam_code', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('admin_emails', models.TextField(default='', help_text='Comma-separated admin contact emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_school.academicyear')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='the_school.classgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to='users.teacher')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examtype')),
                ('grading_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.gradescale')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='the_school.subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-date_conducted'],
                'unique_together': {('subject', 'class_group', 'academic_year', 'exam_type')},
            },
        ),
    ]
