# Generated by Django 5.1.6 on 2025-04-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Score awarded to the student.', max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='Letter grade calculated from the exam’s grading scale.', max_length=3, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='users.student')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
