# Generated by Django 5.1.6 on 2025-04-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_school', '0001_initial'),
        ('users', '0003_alter_teacher_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique department code (e.g., SCI, MAT, ICT).', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name of the department (e.g., Computer Science).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the department’s purpose or focus.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to deactivate departments without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, help_text='Optional: Assign a department head.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to='users.teacher')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code', 'name'), name='unique_department_code_name')],
            },
        ),
    ]
