# Generated by Django 5.1.6 on 2025-04-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_school', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for the academic year (e.g., 2025).', max_length=4, unique=True)),
                ('start_date', models.DateField(help_text='Date when this academic year begins.')),
                ('end_date', models.DateField(help_text='Date when this academic year ends.')),
                ('is_active', models.BooleanField(default=True, help_text='Can users interact with this academic year?')),
                ('is_closed', models.BooleanField(default=False, help_text='Marking as closed prevents further edits or associations.')),
                ('is_current', models.BooleanField(default=False, help_text='The currently in-use academic year. Only one allowed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
    ]
