# Generated by Django 5.1.6 on 2025-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_school', '0003_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', models.PositiveSmallIntegerField(help_text='Numeric value of the grade (e.g., 9 for Grade 9).', unique=True)),
                ('year_level', models.PositiveSmallIntegerField(help_text='Optional internal academic level indicator (e.g., 1 for Grade 9).')),
                ('reference_code', models.CharField(help_text='Short code used internally or on transcripts (e.g., G9, G12).', max_length=10, unique=True)),
                ('display_name', models.CharField(help_text="Display name for UI (e.g., 'Grade 9', 'Form 1').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade Level',
                'verbose_name_plural': 'Grade Levels',
                'ordering': ['grade_number'],
            },
        ),
    ]
