# Generated by Django 5.1.6 on 2025-04-22 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_school', '0004_gradelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, help_text="Auto-generated name like '2025-G9'.", max_length=20, unique=True, verbose_name='Class Group Name')),
                ('academic_year', models.ForeignKey(help_text='The academic year this class group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='the_school.academicyear', verbose_name='Academic Year')),
                ('grade_level', models.ForeignKey(help_text='The grade level assigned to this class group.', on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='the_school.gradelevel', verbose_name='Grade Level')),
            ],
            options={
                'verbose_name': 'Class Group',
                'verbose_name_plural': 'Class Groups',
                'ordering': ['-academic_year', 'grade_level'],
                'unique_together': {('academic_year', 'grade_level')},
            },
        ),
    ]
