# Generated by Django 5.1.6 on 2025-04-22 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_school', '0005_classgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the subject (e.g., Algebra I, Physics).', max_length=100)),
                ('code', models.CharField(editable=False, help_text='Auto-generated subject code (e.g., MAT-G9).', max_length=10, unique=True)),
                ('department', models.ForeignKey(help_text='The department offering this subject (e.g., Mathematics).', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='the_school.department')),
                ('grade_level', models.ForeignKey(help_text='The grade level where this subject is taught.', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='the_school.gradelevel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['grade_level', 'department', 'name'],
                'unique_together': {('department', 'grade_level', 'name')},
            },
        ),
    ]
