# Generated by Django 5.1.6 on 2025-04-24 11:18

import the_school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_school', '0006_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_logo',
            field=models.ImageField(blank=True, default='school_logos/no_logo.png', null=True, upload_to=the_school.models.school_logo_upload_path),
        ),
    ]
